"""Parity test: TS and Python implementations MUST produce identical buckets.

Runs the Python implementation against known-tenant fixtures and asserts the
expected bucket name. The TS implementation has its own test in
the WAVE control plane's storage.test.ts; both must agree on these fixtures.

Run: python3 -m pytest tests/test_parity.py
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from bucket_for_tenant import bucket_for_tenant, all_bucket_names  # noqa: E402


# Fixtures — TS implementation must match these exactly.
# Generated by running Python implementation on each input. If you change the
# hash function or pool size, regenerate ALL fixtures (this is a contract break).
FIXTURES = {
    "tenant_abc": "wave-customer-storage-pool-3",
    "tenant_def": "wave-customer-storage-pool-4",
    "tenant_xyz": "wave-customer-storage-pool-2",
    "01H5XKJ9Z8R7B6Q5P4N3M2L1K0": "wave-customer-storage-pool-0",
    "t_1": "wave-customer-storage-pool-3",
    "t_2": "wave-customer-storage-pool-0",
}


def test_pool_size_default():
    assert len(all_bucket_names()) == 10


def test_pool_naming():
    names = all_bucket_names()
    assert names[0] == "wave-customer-storage-pool-0"
    assert names[-1] == "wave-customer-storage-pool-9"


def test_empty_tenant_id_rejected():
    try:
        bucket_for_tenant("")
        assert False, "expected ValueError"
    except ValueError:
        pass


def test_deterministic():
    # Determinism is the load-bearing property — any non-determinism = 404s.
    for tenant_id in FIXTURES:
        a = bucket_for_tenant(tenant_id)
        b = bucket_for_tenant(tenant_id)
        assert a == b


def test_known_fixtures():
    # NOTE: these are the parity fixtures the TS test must also assert against.
    # If you change the hash function or first-4-bytes-big-endian convention,
    # regenerate ALL fixtures here AND in test/storage.test.ts.
    for tenant_id, expected in FIXTURES.items():
        assert bucket_for_tenant(tenant_id) == expected, (
            f"parity break for {tenant_id}: got {bucket_for_tenant(tenant_id)}, expected {expected}"
        )


if __name__ == "__main__":
    # Self-check without pytest
    test_pool_size_default()
    test_pool_naming()
    test_empty_tenant_id_rejected()
    test_deterministic()
    test_known_fixtures()
    print("OK — all parity tests pass")
