#!/usr/bin/env python3
"""emit.py — turn the gate registry into config, and verify configs haven't drifted from it.

The registry (registry.yaml) declares each left-shift gate once. This script is the other half:
it generates the `repo: local` pre-commit hook block from the registry, and — the part that makes
the registry authoritative — `--check` fails CI if the live .pre-commit-config.yaml doesn't match.

Usage:
  emit.py --precommit            print the generated `repo: local` hook entries (paste/inspect)
  emit.py --check [CONFIG]       verify CONFIG (default .pre-commit-config.yaml) matches the registry
  emit.py --list                 human summary of registered gates

Pure stdlib + pyyaml (already a foundation pre-commit dep).
"""
from __future__ import annotations

import argparse
import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
REGISTRY = os.path.join(HERE, "registry.yaml")


def load_gates(path: str = REGISTRY) -> list[dict]:
    with open(path, encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
    return data.get("gates", [])


def hook_entry(g: dict) -> dict:
    """The pre-commit hook a gate should produce (the contract --check enforces)."""
    h = {
        "id": g["id"],
        "name": g["name"],
        "entry": g["script"],
        "language": "script",
    }
    stage = g.get("stage", "pre-commit")
    if stage != "pre-commit":
        h["stages"] = [stage]
    if g.get("files"):
        h["files"] = g["files"]
    if g.get("exclude"):
        h["exclude"] = g["exclude"]
    if g.get("always_run"):
        h["always_run"] = True
    h["pass_filenames"] = bool(g.get("pass_filenames", True))
    return h


def render_precommit(gates: list[dict]) -> str:
    lines = ["      # >>> gates:registry — generated by frameworks/gates/emit.py; edit registry.yaml, not here"]
    for g in gates:
        h = hook_entry(g)
        lines.append(f"      - id: {h['id']}")
        lines.append(f"        name: {h['name']}")
        lines.append(f"        entry: {h['entry']}")
        lines.append("        language: script")
        if "stages" in h:
            lines.append(f"        stages: [{', '.join(h['stages'])}]")
        if "files" in h:
            lines.append(f"        files: '{h['files']}'")
        if "exclude" in h:
            lines.append(f"        exclude: '{h['exclude']}'")
        if h.get("always_run"):
            lines.append("        always_run: true")
        lines.append(f"        pass_filenames: {str(h['pass_filenames']).lower()}")
    lines.append("      # <<< gates:registry")
    return "\n".join(lines)


def find_local_hooks(config_path: str) -> dict[str, dict]:
    with open(config_path, encoding="utf-8") as fh:
        cfg = yaml.safe_load(fh) or {}
    out: dict[str, dict] = {}
    for repo in cfg.get("repos", []):
        if repo.get("repo") == "local":
            for hook in repo.get("hooks", []):
                out[hook.get("id")] = hook
    return out


def check(config_path: str) -> int:
    gates = load_gates()
    if not os.path.exists(config_path):
        print(f"::error::{config_path} not found")
        return 1
    live = find_local_hooks(config_path)
    errs: list[str] = []
    for g in gates:
        gid = g["id"]
        want = hook_entry(g)
        got = live.get(gid)
        if got is None:
            errs.append(f"{gid}: declared in registry but MISSING from {config_path}")
            continue
        if got.get("entry") != want["entry"]:
            errs.append(f"{gid}: entry '{got.get('entry')}' != registry '{want['entry']}'")
        want_stages = want.get("stages", ["pre-commit"])
        got_stages = got.get("stages", ["pre-commit"])
        if sorted(got_stages) != sorted(want_stages):
            errs.append(f"{gid}: stages {got_stages} != registry {want_stages}")
        if want.get("files") and got.get("files") != want["files"]:
            errs.append(f"{gid}: files '{got.get('files')}' != registry '{want['files']}'")
    for e in errs:
        print(f"::error::gate-drift: {e}")
    if errs:
        print(f"gate-registry drift: {len(errs)} mismatch(es). Run emit.py --precommit and reconcile.")
        return 1
    print(f"gate-registry: ✓ {len(gates)} gates match {config_path}")
    return 0


def list_gates() -> int:
    gates = load_gates()
    print(f"{'id':24} {'stage':12} {'ci_job':22} script")
    for g in gates:
        print(f"{g['id']:24} {g.get('stage', 'pre-commit'):12} {str(g.get('ci_job', '-')):22} {g['script']}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--precommit", action="store_true", help="print generated repo:local hook block")
    ap.add_argument("--check", nargs="?", const=".pre-commit-config.yaml", help="verify config matches registry")
    ap.add_argument("--list", action="store_true", help="summary of registered gates")
    args = ap.parse_args()
    if args.precommit:
        print(render_precommit(load_gates()))
        return 0
    if args.check is not None:
        return check(args.check)
    if args.list:
        return list_gates()
    ap.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
